name: Deploy Session Notes to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # TODO: add command to fail CI if any of the following commands have non-zero exit code

      - name: Install Swift
        uses: swift-actions/setup-swift@v2

      - name: Add Session Metadata
        run: swift run add-session-metadata

      - name: Generate Contributors
        run: swift run generate-contributors

      - name: Generate Missing Notes
        run: swift run generate-missing-notes
      
      - name: Build Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target WWDCNotes \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path WWDCNotes \
            --output-path ./docs

      # TODO: fix favicon, the below code is not working as expected
      - name: Override Favicons
        run: |
          rm ./docs/favicon.svg
          rm ./docs/favicon.ico
          cp ./favicon.ico ./docs/favicon.ico
      
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: docs
